language: ruby
cache: bundler
before_install:
  - gem install bundler
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
notifications:
  email:
    on_failure: never
    on_success: never